<a href="https://colab.research.google.com/github/WebbD777/AN_Codes/blob/main/FiniteDifferenceLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math
import matplotlib.pyplot as plt
import numpy as np

# Equation is: y'' + y - 1 = 0
## BC: y(0)=0 , y(1)=0
h = 0.25

yn-1(1 + h/2 * 0)

yn(-2 - h^2 * 1)

yn+1(1-h/2 * 0 )

r = 1*h^2

In [ ]:
a , b = 0 , 1
N  = 4
h = (b-a)/N
step=0
xj = 0
j = 0

# define array
A= np.zeros((N-1,N-1))
while j <= N-2:

  if j != 0:
    A[j, j-1] = 1

  A[j, j] = -2 -h**2

  if j < N - 2:
    A[j, j+1] = 1

  xj += h
  j = j + 1

print(A)

# Define soln array
b = np.zeros(N-1)
b[0] = h**2 * 1 - (1 + h/2*1)*0
b[1:-1] = h**2 * 1
b[-1] = h**2 * 1 - (1 + h/2*1)*0
print(b)

# solve system eqns
y = np.linalg.solve(A, b)
print(y)

[[-2.0625  1.      0.    ]
 [ 1.     -2.0625  1.    ]
 [ 0.      1.     -2.0625]]
[0.0625 0.0625 0.0625]
[-0.08492201 -0.11265165 -0.08492201]
